# Generated by Django 5.1.1 on 2024-10-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_number_of_votes_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
